Repository liquibase/liquibase-mongodb, pull requests merged in 2023-07, with the labels that each got.

#390 DAT-15272
  .github/release-drafter.yml
  .github/workflows/create-release.yml
  .github/workflows/label-pr.yml
  .github/workflows/release-drafter.yml
Labels: TypeEnhancement

#392 DAT-15272
  .github/release-drafter.yml
  .github/workflows/create-release.yml
  .github/workflows/release-drafter.yml
Labels: skipReleaseNotes

#391 [DAT-15279] Implement new ChangeLogHistoryService interface methods
  pom.xml
  src/main/java/liquibase/ext/mongodb/changelog/MongoHistoryService.java
  src/main/java/liquibase/ext/mongodb/database/MongoLiquibaseDatabase.java
  src/main/java/liquibase/nosql/changelog/AbstractNoSqlHistoryService.java
  src/main/java/liquibase/nosql/executor/NoSqlExecutor.java
  src/test/java/liquibase/ext/AbstractMongoIntegrationTest.java
  src/test/java/liquibase/ext/MongoLiquibaseIT.java
  src/test/java/liquibase/ext/MongoLiquibaseJsonIT.java
  src/test/java/liquibase/ext/mongodb/change/AdminCommandChangeTest.java
  src/test/java/liquibase/ext/mongodb/change/CreateCollectionChangeTest.java
  src/test/java/liquibase/ext/mongodb/change/CreateIndexChangeTest.java
  src/test/java/liquibase/ext/mongodb/change/DropIndexChangeTest.java
  src/test/java/liquibase/ext/mongodb/change/InsertManyChangeTest.java
  src/test/java/liquibase/ext/mongodb/change/InsertOneChangeTest.java
  src/test/java/liquibase/ext/mongodb/change/RunCommandChangeTest.java
  src/test/java/liquibase/ext/mongodb/changelog/MongoHistoryServiceIT.java
  src/test/java/liquibase/ext/mongodb/changelog/MongoHistoryServiceTest.java
  src/test/java/liquibase/ext/mongodb/changelog/MongoRanChangeSetToDocumentConverterTest.java
Labels: TypeEnhancement, breakingChanges

#394 [DAT-15373] Fix checksum empty spaces validation
  src/main/java/liquibase/ext/mongodb/change/AbstractMongoChange.java
  src/main/java/liquibase/ext/mongodb/change/AdminCommandChange.java
  src/main/java/liquibase/ext/mongodb/change/CreateCollectionChange.java
  src/main/java/liquibase/ext/mongodb/change/CreateIndexChange.java
  src/main/java/liquibase/ext/mongodb/change/DropIndexChange.java
  src/main/java/liquibase/ext/mongodb/change/InsertManyChange.java
  src/main/java/liquibase/ext/mongodb/change/InsertOneChange.java
  src/main/java/liquibase/ext/mongodb/change/RunCommandChange.java
  src/test/java/liquibase/ext/MongoLiquibaseIT.java
  src/test/java/liquibase/ext/MongoLiquibaseJsonIT.java
  src/test/java/liquibase/ext/mongodb/change/AdminCommandChangeTest.java
  src/test/java/liquibase/ext/mongodb/change/CreateCollectionChangeTest.java
  src/test/java/liquibase/ext/mongodb/change/CreateIndexChangeTest.java
  src/test/java/liquibase/ext/mongodb/change/DropIndexChangeTest.java
  src/test/java/liquibase/ext/mongodb/change/InsertManyChangeTest.java
  src/test/java/liquibase/ext/mongodb/change/InsertOneChangeTest.java
  src/test/java/liquibase/ext/mongodb/change/RunCommandChangeTest.java
  src/test/java/liquibase/ext/mongodb/changelog/MongoHistoryServiceIT.java
Labels: TypeEnhancement

#397 Update version to 4.23.0-SNAPSHOT in pom.xml
  pom.xml
Labels: dependencies, notableChanges

#400 DAT-15386 update the extension to use our reusable workflows
  .github/workflows/attach-artifact-release.yml
  .github/workflows/create-release.yml
  .github/workflows/release-published.yml
  .github/workflows/snyk-nightly.yml
  .github/workflows/test.yml
  pom.xml
Labels: TypeBug

#401 DAT-15386 update the extension to use our reusable workflows
  .github/workflows/release-drafter.yml
  .github/workflows/release-published.yml
  .github/workflows/test.yml
  pom.xml
  test-project/pom.xml
Labels: TypeBug

#403 Dat 15386
  pom.xml
Labels: TypeBug

#404 feat(upload_zip.sh): add script to upload zip file as an asset to a G…
  .github/upload_zip.sh
  .github/workflows/attach-artifact-release.yml
  .github/workflows/release-published.yml
Labels: TypeBug

#405 Dat 15386
  .github/workflows/get_draft_release.sh
  pom.xml
Labels: TypeBug

#407 Dat 15386
  .github/upload_zip.sh
  .github/workflows/attach-artifact-release.yml
  .github/workflows/get_draft_release.sh
  pom.xml
Labels: TypeBug

#408 Dat 15386
  .github/workflows/attach-artifact-release.yml
  .github/workflows/get_draft_release.sh
  pom.xml
Labels: TypeBug

#410 Update dependabot.yml
  .github/dependabot.yml
Labels: skipReleaseNotes

#411 DAT-15386 Automatically bump artifact version
  .github/workflows/attach-artifact-release.yml
  .github/workflows/create-release.yml
  .github/workflows/release-published.yml
  .github/workflows/snyk-nightly.yml
  pom.xml
Labels: notableChanges
