Repository liquibase/liquibase-mongodb, pull requests merged in 2023-10, with the labels that each got.

#447 add workflow dispatch for create release
  .github/workflows/create-release.yml
Labels: skipReleaseNotes

#432 [DAT-15338] Add mongodb connection patterns to hide credentials in logs
  pom.xml
  src/main/java/liquibase/ext/mongodb/database/MongodbConnectionPatterns.java
  src/main/resources/META-INF/services/liquibase.database.jvm.ConnectionPatterns
Labels: TypeEnhancement, breakingChanges

#450 [no-jira] updated requirement to core 4.24
  README.md
Labels: documentation, skipReleaseNotes

#451 [no-jira] update extension version to 4.24
  pom.xml
Labels: skipReleaseNotes

#437 DAT 15505 Liquibase Extensions Parent POM
  .github/workflows/attach-artifact-release.yml
  .github/workflows/build-nightly.yml
  .github/workflows/create-release.yml
  .github/workflows/release-published.yml
  .github/workflows/snyk-nightly.yml
  .github/workflows/test.yml
  pom.xml
Labels: TypeEnhancement

#462 DAT-15598 DevOps :: Create reusable workflow for CodeQL scanning
  .github/workflows/codeql.yml
Labels: TypeEnhancement, skipReleaseNotes

#466 DAT-16142 DevOps :: Liquibase MongoDB Extension : sonar cloud scans showing as 0.0% Coverage
  .github/workflows/attach-artifact-release.yml
  .github/workflows/build-nightly.yml
  .github/workflows/codeql.yml
  .github/workflows/create-release.yml
  .github/workflows/release-published.yml
  .github/workflows/test.yml
  pom.xml
Labels: skipReleaseNotes
