Repository liquibase/liquibase-mongodb, pull requests merged in 2024-04, with the labels that each got.

#518 DAT-17414 upgrade docker compose to v2
  .github/workflows/test.yml
  FerretDB.md
Labels: TypeEnhancement

#521 [no jira] Add liquibase version as requirement for LPM
  pom.xml
Labels: skipReleaseNotes

#522 [DAT-17365] Release lock even if update fails on timeout
  src/main/java/liquibase/ext/mongodb/lockservice/MongoLockService.java
Labels: TypeBug
