Repository liquibase/liquibase-mongodb, pull requests merged in 2024-03, with the labels that each got.

#510 DAT-15503. added mongodb atlas 7 to the test.yml
  .github/workflows/build-nightly.yml
  .github/workflows/test.yml
  src/test/groovy/liquibase/harness/compatibility/foundational/HarnessNoSqlCompatibility.groovy
  src/test/resources/harness-config-cloud.yml
Labels: TypeTest

#502 [DAT-16074] Implement user friendly message for if required dependencies are not available
  src/main/java/liquibase/ext/mongodb/database/MongoConnection.java
Labels: TypeEnhancement

#504 DAT-15502. added the compoud wildcard index(new MongoDB 7 feature) to createIndex test
  src/test/resources/liquibase/harness/compatibility/foundational/changelogs/nosql/createIndex.json
  src/test/resources/liquibase/harness/compatibility/foundational/changelogs/nosql/createIndex.xml
  src/test/resources/liquibase/harness/compatibility/foundational/changelogs/nosql/createIndex.yaml
  src/test/resources/liquibase/harness/compatibility/foundational/expectedResultSet/json_changelog/createIndex.json
  src/test/resources/liquibase/harness/compatibility/foundational/expectedResultSet/xml_changelog/createIndex.json
  src/test/resources/liquibase/harness/compatibility/foundational/expectedResultSet/yaml_changelog/createIndex.json
Labels: TypeTest

#515 Revert "build(deps): bump liquibase/build-logic from 0.6.6 to 0.6.8"
  .github/workflows/attach-artifact-release.yml
  .github/workflows/build-nightly.yml
  .github/workflows/codeql.yml
  .github/workflows/create-release.yml
  .github/workflows/release-published.yml
  .github/workflows/test.yml
Labels: dependencies, sdou
